// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUMb-1hY2Dm3BGH69jyQYoN49_4ZhPLJU',
    storageBucket: 'netflex-d6a6c.appspot.com',
    googleAppID: 'dbpark@maprex.co.kr',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfZbX__ssLMyLDs3-pluNwVG2nlc2pC1E',
    storageBucket: 'netflex-d6a6c.appspot.com',
    googleAppID: 'dbpark@maprex.co.kr',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-xaeXso9NP6EByzoI7UkqDhCwktryz_A',
    projectID: 'netflex-d6a6c',
    storageBucket: 'netflex-d6a6c.appspot.com',
    bundleID: 'com.example.cloneNetflix',
    googleAppID: 'dbpark@maprex.co.kr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-xaeXso9NP6EByzoI7UkqDhCwktryz_A',
    projectID: 'netflex-d6a6c',
    storageBucket: 'netflex-d6a6c.appspot.com',
    clientID:
        '1035556304888-1hvmo013hctns7i7d4mten6iicuor5fm.apps.googleusercontent.com',
    bundleID: 'com.example.cloneNetflix',
    googleAppID: 'dbpark@maprex.co.kr',
  );
}
